param(
    [string]$BaseUrl = "http://localhost:8000"
)

$ErrorActionPreference = "Stop"

function Write-Step {
    param([string]$Message)
    Write-Host "[demo-check] $Message"
}

Write-Step "Checking backend health at $BaseUrl/health"
$health = Invoke-RestMethod -Method Get -Uri "$BaseUrl/health"
if ($health.status -ne "healthy") {
    throw "Health endpoint did not return healthy status."
}

Write-Step "Checking scenario list"
$scenarioList = Invoke-RestMethod -Method Get -Uri "$BaseUrl/api/v1/scenarios?limit=1"

if (-not $scenarioList.items -or $scenarioList.items.Count -eq 0) {
    Write-Step "No scenarios found; creating one demo scenario"
    $body = @{
        name = "Demo Smoke Scenario"
        description = "Submission demo scenario generated by scripts/demo_smoke_check.ps1"
        budget_million_usd = 5.0
        expected_roi_percent = 30.0
        risk_level = 5
        team_readiness = 7
    } | ConvertTo-Json

    $created = Invoke-RestMethod `
        -Method Post `
        -Uri "$BaseUrl/api/v1/scenarios" `
        -Body $body `
        -ContentType "application/json"

    $scenarioId = $created.scenario_id
} else {
    $scenarioId = $scenarioList.items[0].id
}

Write-Step "Running simulation for scenario $scenarioId"
$elapsed = Measure-Command {
    $simulation = Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/v1/scenarios/$scenarioId/simulate"
}

if (-not $simulation.final_decision) {
    throw "Simulation response did not include final_decision."
}

Write-Step "Simulation OK: decision=$($simulation.final_decision), score=$($simulation.final_score), seconds=$([math]::Round($elapsed.TotalSeconds, 2))"
Write-Step "Demo smoke check passed"
