param(
    [string]$BaseUrl       = "http://localhost:8010",
    [string]$OllamaBaseUrl = "http://localhost:11434",
    [string]$OllamaModel   = "qwen2.5:7b",
    [int]   $SimulateTimeoutSec = 180
)

$ErrorActionPreference = "Stop"

function Write-Step {
    param([string]$Message)
    Write-Host "[llm-smoke] $Message"
}

# 1) Ollama erisilebilir mi?
Write-Step "Checking Ollama at $OllamaBaseUrl/api/tags"
try {
    $tags = Invoke-RestMethod -Method Get -Uri "$OllamaBaseUrl/api/tags" -TimeoutSec 10
} catch {
    throw "Ollama'ya $OllamaBaseUrl uzerinden ulasilamadi. 'ollama serve' calisiyor mu? Hata: $($_.Exception.Message)"
}

$modelNames = @($tags.models | ForEach-Object { $_.name })
if (-not ($modelNames -contains $OllamaModel)) {
    throw "Ollama modeli '$OllamaModel' yuklu degil. 'ollama pull $OllamaModel' calistirin. Mevcut modeller: $($modelNames -join ', ')"
}

# 2) Modeli isit (cold-start gecikmesini demo oncesi yut)
Write-Step "Warming model '$OllamaModel' (one short completion)"
$warmBody = @{
    model  = $OllamaModel
    prompt = "ping"
    stream = $false
} | ConvertTo-Json
$null = Invoke-RestMethod -Method Post -Uri "$OllamaBaseUrl/api/generate" -Body $warmBody -ContentType "application/json" -TimeoutSec 120

# 3) LLM backend health
Write-Step "Checking LLM backend health at $BaseUrl/health"
$health = Invoke-RestMethod -Method Get -Uri "$BaseUrl/health" -TimeoutSec 10
if ($health.status -ne "healthy") {
    throw "LLM backend health endpoint did not return healthy."
}

# 4) Senaryo bul ya da olustur
Write-Step "Locating a scenario for LLM simulation"
$scenarioList = Invoke-RestMethod -Method Get -Uri "$BaseUrl/api/v1/scenarios?limit=1" -TimeoutSec 10
if (-not $scenarioList.items -or $scenarioList.items.Count -eq 0) {
    Write-Step "No scenarios found; creating one LLM demo scenario"
    $body = @{
        name = "LLM Bonus Smoke Scenario"
        description = "Bonus LLM demo scenario generated by scripts/llm_smoke_check.ps1"
        budget_million_usd = 5.0
        expected_roi_percent = 30.0
        risk_level = 5
        team_readiness = 7
    } | ConvertTo-Json
    $created = Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/v1/scenarios" -Body $body -ContentType "application/json" -TimeoutSec 30
    $scenarioId = $created.scenario_id
} else {
    $scenarioId = $scenarioList.items[0].id
}

# 5) LLM-acik simulation (uzun timeout)
Write-Step "Running LLM simulation for scenario $scenarioId (timeout ${SimulateTimeoutSec}s)"
$elapsed = Measure-Command {
    $simulation = Invoke-RestMethod -Method Post -Uri "$BaseUrl/api/v1/scenarios/$scenarioId/simulate" -TimeoutSec $SimulateTimeoutSec
}

if (-not $simulation.final_decision) {
    throw "LLM simulation response did not include final_decision."
}

Write-Step "LLM simulation OK: decision=$($simulation.final_decision), score=$($simulation.final_score), seconds=$([math]::Round($elapsed.TotalSeconds, 2))"
Write-Step "LLM smoke check passed"
